# Generated by Django 4.2.2 on 2023-10-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='time',
            field=models.TimeField(default=''),
        ),
    ]
