# Generated by Django 4.2.2 on 2023-11-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_profile_crud_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.profile'),
        ),
    ]
