# Generated by Django 4.2.2 on 2023-10-21 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_crud_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time, null=True),
        ),
    ]
