# Generated by Django 4.2.2 on 2023-11-19 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
